export const ERROR_CODE = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  INVALID_AUTH_TOKEN: "INVALID_AUTH_TOKEN",
  AUTH_SIGNUP_FAILED: "AUTH_SIGNUP_FAILED",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT_FAILED: "AUTH_LOGOUT_FAILED",

  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_ALREADY_EXISTS: "PROFILE_ALREADY_EXISTS",
  PROFILE_READ_FAILED: "PROFILE_READ_FAILED",
  PROFILE_CREATE_FAILED: "PROFILE_CREATE_FAILED",
  PROFILE_UPDATE_FAILED: "PROFILE_UPDATE_FAILED",

  MEDICATION_NOT_FOUND: "MEDICATION_NOT_FOUND",
  MEDICATION_READ_FAILED: "MEDICATION_READ_FAILED",
  MEDICATION_CREATE_FAILED: "MEDICATION_CREATE_FAILED",
  MEDICATION_UPDATE_FAILED: "MEDICATION_UPDATE_FAILED",
  MEDICATION_DELETE_FAILED: "MEDICATION_DELETE_FAILED",

  MEDICATION_CATALOG_READ_FAILED: "MEDICATION_CATALOG_READ_FAILED",
  MEDICATION_CATALOG_NOT_FOUND: "MEDICATION_CATALOG_NOT_FOUND",
  MEDICATION_CATALOG_CREATE_FAILED: "MEDICATION_CATALOG_CREATE_FAILED",
  MEDICATION_CATALOG_UPDATE_FAILED: "MEDICATION_CATALOG_UPDATE_FAILED",
  MEDICATION_CATALOG_DELETE_FAILED: "MEDICATION_CATALOG_DELETE_FAILED",

  SCHEDULE_NOT_FOUND: "SCHEDULE_NOT_FOUND",
  SCHEDULE_READ_FAILED: "SCHEDULE_READ_FAILED",
  SCHEDULE_CREATE_FAILED: "SCHEDULE_CREATE_FAILED",
  SCHEDULE_UPDATE_FAILED: "SCHEDULE_UPDATE_FAILED",
  SCHEDULE_DELETE_FAILED: "SCHEDULE_DELETE_FAILED",
  SCHEDULE_REMINDER_READ_FAILED: "SCHEDULE_REMINDER_READ_FAILED",
  SCHEDULE_REMINDER_CREATE_FAILED: "SCHEDULE_REMINDER_CREATE_FAILED",

  DAILY_PLAN_READ_FAILED: "DAILY_PLAN_READ_FAILED",
  INTAKE_READ_FAILED: "INTAKE_READ_FAILED",
  INTAKE_CREATE_FAILED: "INTAKE_CREATE_FAILED",
  INTAKE_NOT_ALLOWED: "INTAKE_NOT_ALLOWED",

  INVALID_UPLOAD_FILE: "INVALID_UPLOAD_FILE",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  STATIC_FILE_NOT_FOUND: "STATIC_FILE_NOT_FOUND",
  STATIC_FILE_READ_FAILED: "STATIC_FILE_READ_FAILED",
  STATIC_FILE_CREATE_FAILED: "STATIC_FILE_CREATE_FAILED",

  AI_SCAN_FAILED: "AI_SCAN_FAILED",
  AI_SCAN_ATTEMPT_CREATE_FAILED: "AI_SCAN_ATTEMPT_CREATE_FAILED",
  AI_SCAN_ATTEMPT_READ_FAILED: "AI_SCAN_ATTEMPT_READ_FAILED",
  AI_SCAN_ATTEMPT_UPDATE_FAILED: "AI_SCAN_ATTEMPT_UPDATE_FAILED",
  AI_SCAN_ATTEMPT_NOT_FOUND: "AI_SCAN_ATTEMPT_NOT_FOUND",

  CAREGIVER_LINK_NOT_FOUND: "CAREGIVER_LINK_NOT_FOUND",
  CAREGIVER_LINK_ALREADY_EXISTS: "CAREGIVER_LINK_ALREADY_EXISTS",
  CAREGIVER_LINK_READ_FAILED: "CAREGIVER_LINK_READ_FAILED",
  CAREGIVER_LINK_CREATE_FAILED: "CAREGIVER_LINK_CREATE_FAILED",
  CAREGIVER_LINK_UPDATE_FAILED: "CAREGIVER_LINK_UPDATE_FAILED",

  PUSH_TOKEN_NOT_FOUND: "PUSH_TOKEN_NOT_FOUND",
  PUSH_TOKEN_READ_FAILED: "PUSH_TOKEN_READ_FAILED",
  PUSH_TOKEN_CREATE_FAILED: "PUSH_TOKEN_CREATE_FAILED",
  PUSH_TOKEN_UPDATE_FAILED: "PUSH_TOKEN_UPDATE_FAILED",

  NOTIFICATION_EVENT_READ_FAILED: "NOTIFICATION_EVENT_READ_FAILED",
  NOTIFICATION_EVENT_CREATE_FAILED: "NOTIFICATION_EVENT_CREATE_FAILED",
  NOTIFICATION_EVENT_UPDATE_FAILED: "NOTIFICATION_EVENT_UPDATE_FAILED",
  NOTIFICATION_EVENT_NOT_FOUND: "NOTIFICATION_EVENT_NOT_FOUND",
  EXPO_PUSH_SEND_FAILED: "EXPO_PUSH_SEND_FAILED",

  SAFETY_CHECK_CREATE_FAILED: "SAFETY_CHECK_CREATE_FAILED",
  SAFETY_CHECK_READ_FAILED: "SAFETY_CHECK_READ_FAILED",
  SAFETY_CHECK_NOT_FOUND: "SAFETY_CHECK_NOT_FOUND",
} as const;
