export const ERROR_CODE = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  INVALID_AUTH_TOKEN: "INVALID_AUTH_TOKEN",
  AUTH_SIGNUP_FAILED: "AUTH_SIGNUP_FAILED",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT_FAILED: "AUTH_LOGOUT_FAILED",

  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_ALREADY_EXISTS: "PROFILE_ALREADY_EXISTS",
  PROFILE_READ_FAILED: "PROFILE_READ_FAILED",
  PROFILE_CREATE_FAILED: "PROFILE_CREATE_FAILED",
  PROFILE_UPDATE_FAILED: "PROFILE_UPDATE_FAILED",

  MEDICATION_NOT_FOUND: "MEDICATION_NOT_FOUND",
  MEDICATION_READ_FAILED: "MEDICATION_READ_FAILED",
  MEDICATION_CREATE_FAILED: "MEDICATION_CREATE_FAILED",
  MEDICATION_UPDATE_FAILED: "MEDICATION_UPDATE_FAILED",
  MEDICATION_DELETE_FAILED: "MEDICATION_DELETE_FAILED",

  MEDICATION_CATALOG_READ_FAILED: "MEDICATION_CATALOG_READ_FAILED",
  MEDICATION_CATALOG_NOT_FOUND: "MEDICATION_CATALOG_NOT_FOUND",
  MEDICATION_CATALOG_CREATE_FAILED: "MEDICATION_CATALOG_CREATE_FAILED",
  MEDICATION_CATALOG_UPDATE_FAILED: "MEDICATION_CATALOG_UPDATE_FAILED",
  MEDICATION_CATALOG_DELETE_FAILED: "MEDICATION_CATALOG_DELETE_FAILED",

  SCHEDULE_NOT_FOUND: "SCHEDULE_NOT_FOUND",
  SCHEDULE_READ_FAILED: "SCHEDULE_READ_FAILED",
  SCHEDULE_CREATE_FAILED: "SCHEDULE_CREATE_FAILED",
  SCHEDULE_UPDATE_FAILED: "SCHEDULE_UPDATE_FAILED",
  SCHEDULE_DELETE_FAILED: "SCHEDULE_DELETE_FAILED",

  DAILY_PLAN_READ_FAILED: "DAILY_PLAN_READ_FAILED",
  INTAKE_READ_FAILED: "INTAKE_READ_FAILED",

  INVALID_UPLOAD_FILE: "INVALID_UPLOAD_FILE",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  STATIC_FILE_NOT_FOUND: "STATIC_FILE_NOT_FOUND",
  STATIC_FILE_READ_FAILED: "STATIC_FILE_READ_FAILED",
  STATIC_FILE_CREATE_FAILED: "STATIC_FILE_CREATE_FAILED",

  AI_SCAN_FAILED: "AI_SCAN_FAILED",
  AI_SCAN_ATTEMPT_CREATE_FAILED: "AI_SCAN_ATTEMPT_CREATE_FAILED",
} as const;
